---
apiVersion: v1
kind: Service
metadata:
  name: jig-workshop-worker-svc
  namespace: jig-workshop-worker
  labels:
    app: jig-workshop-worker
    app.kubernetes.io/name: jig-workshop-worker
    app.kubernetes.io/part-of: jig-workshop-worker
spec:
  ports:
    - port: 8080
      name: web
  selector:
    app: jig-workshop-worker
