apiVersion: v1
kind: ConfigMap
metadata:
  name: jig-env
  namespace: jig-workshop-worker
  labels:
    app: jig
data:
  .env: |
    APP_NAME=Jig
    APP_ENV=local
    APP_KEY=base64:aFOsf9UVdLX8bc9akpR9xEGIEx7+c4UShwPZ7XPrmCI=
    APP_DEBUG=false
    APP_URL=https://localhost

    LOG_CHANNEL=stack

    DB_CONNECTION=mysql
    DB_HOST=mysql
    DB_PORT=3306
    DB_DATABASE=jigdb
    DB_USERNAME=root
    DB_PASSWORD=sup3rS3cr3t

    BROADCAST_DRIVER=log
    CACHE_DRIVER=database
    QUEUE_CONNECTION=sync
    SESSION_DRIVER=database
    SESSION_LIFETIME=120

    REDIS_HOST=127.0.0.1
    REDIS_PASSWORD=null
    REDIS_PORT=6379

    MAIL_DRIVER=smtp
    MAIL_HOST=smtp.sendgrid.net
    MAIL_PORT=587
    MAIL_USERNAME=apikey
    MAIL_PASSWORD=null
    MAIL_ENCRYPTION=tls
    MAIL_FROM_ADDRESS=null
    MAIL_FROM_NAME="${APP_NAME}"

    AWS_ACCESS_KEY_ID=
    AWS_SECRET_ACCESS_KEY=
    AWS_DEFAULT_REGION=us-east-1
    AWS_BUCKET=

    PUSHER_APP_ID=
    PUSHER_APP_KEY=
    PUSHER_APP_SECRET=
    PUSHER_APP_CLUSTER=mt1

    MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
    MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
