---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jig-mysql-pv-volume
  namespace: jig-workshop-worker
  labels:
    app: jig-mysql
    app.kubernetes.io/name: jig-mysql
    app.kubernetes.io/part-of: jig-workshop-worker
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jig-mysql-pv-claim
  namespace: jig-workshop-worker
  labels:
    app: jig-mysql
    app.kubernetes.io/name: jig-mysql
    app.kubernetes.io/part-of: jig-workshop-worker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
